; PlatformIO Project Configuration File for MindMotion MM32G0001 (Pure Bare-Metal with HAL)

[env:disco_f030r8]
platform = ststm32
board = disco_f030r8
; framework = cmsis  <-- Disabled STM32 CMSIS framework compilation to remove stm32 workarounds

; Override the board settings to match your generic Cortex-M0 (MM32G0001)
board_build.cpu = cortex-m0

upload_protocol = custom
upload_command = pyocd flash --pack "C:\Users\AKSHAY\Desktop\code\projects\custom_servo\mm32_test\MindMotion.MM32G0001_DFP.1.0.1.pack" --target mm32g0001a1tc $SOURCE

; Manually override memory sizes to match MM32G0001 specs
board_upload.maximum_size = 16384
board_upload.maximum_ram_size = 2048
board_build.ldscript = custom.ld

; Enable MindMotion Standard Peripheral Driver compilation
build_flags = 
  -D USE_STDPERIPH_DRIVER

; Configure Serial Monitor baud rate
monitor_speed = 250000