; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:disco_f030r8]
platform = ststm32
board = disco_f030r8
framework = cmsis

; Override the board settings to match your generic Cortex-M0 (MM32G0001)
board_build.cpu = cortex-m0

; Force PlatformIO to use your Pi Pico Debug Probe via SWD
upload_protocol = cmsis-dap
debug_tool = cmsis-dap
; Manually override memory sizes to match MM32G0001 specs
board_upload.maximum_size = 16384
board_upload.maximum_ram_size = 2048