; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:genericCH32V003J4M6]
platform = ch32v
board = genericCH32V003J4M6
framework = ch32v003fun

upload_protocol = custom
upload_flags =
    -f
    interface/cmsis-dap.cfg
    -f
    target/wch-riscv.cfg
    -c
    init
    -c
    halt
    -c
    program {$SOURCE} verify reset exit

upload_command = "${platformio.packages_dir}/tool-openocd-riscv-wch/bin/openocd" $UPLOAD_FLAGS