[env:genericCH32V003J4M6]
platform = ch32v
board = genericCH32V003J4M6
framework = ch32v003fun

; Use GDB to upload over the PicoRVD virtual serial port (COM6)
upload_protocol = custom
upload_command = "$PROJECT_PACKAGES_DIR/toolchain-riscv/bin/riscv-wch-elf-gdb.exe" -nx -batch -ex "set remotetimeout 2" -ex "target extended-remote COM6" -ex "load" -ex "detach" -ex "quit" $SOURCE
